#Workflow name
name: .NET Build and Test

on:
  #Triggers on push or pull request (Webhook)
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  #Manual trigger (Run by button)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    #.sln file path
    - name: Restore dependencies
      run: dotnet restore UserApi/UserApi.sln

    #Build with .sln file path
    - name: Build
      run: dotnet build UserApi/UserApi.sln --no-restore

    #Test with .sln file path
    - name: Test
      run: dotnet test UserApi/UserApi.sln --no-build --verbosity normal
