#Workflow Name
name: .NET Build and Test

on:
  #Webhook
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  #Manual trigger (Run by button)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        #Matches project's .NET version (8.0.x)
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    #Build project
    - name: Build
      run: dotnet build --no-restore

    #Run tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
